package in.foodDelivery.foodiesapi.io;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/*This declares the FoodRequest class, which represents the
 data structure that clients will send to your API when they
  want to create a new food item.
 */

/*Notice that FoodRequest does not contain the id or imageUrl fields. This is because:

The id is typically generated by the database when a new food
 item is created. Clients don't usually provide the ID when
  creating a new resource.
The imageUrl is likely handled separately, possibly
through a file upload mechanism, and then associated with the
FoodEntity on the server-side.*/

@Data
@AllArgsConstructor
@NoArgsConstructor
public class FoodRequest { //FoodRequest to store the food details
    private String name;
    private String description;
    private double price;
    private String category;
}
